spring.application.name=card
server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/chefcard
spring.datasource.username=chefcard
spring.datasource.password=chefcard
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
